version: "3"

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - env
    environment:
      COMPOSE_HTTP_TIMEOUT: 3600
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      pgnet:


  phonemics:
    image: phonemics:latest
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DEPLOYMENT: phonemics
      COMPOSE_HTTP_TIMEOUT: 3600
      LC_CTYPE: en_US.UTF-8
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    env_file: env
    command: >
      bash -c '
      python3 src/manage.py migrate &&
      python3 src/manage.py runserver 0.0.0.0:8000'


volumes:
  pgdata:
networks:
  pgnet:
