export const KEYS = [
  [
    { id: 1, english: "a", arabic: "\u064e", color: "#D8BFD8" },
    { id: 2, english: "b", arabic: "\u064f", color: "#D8BFD8" },
    { id: 3, english: "c", arabic: "\u0650", color: "#D8BFD8" },
    { id: 4, english: "d", arabic: "\u0642", color: "#ADD8E6" },
    { id: 5, english: "e", arabic: "\u062c", color: "#FAEBD7" },
    { id: 6, english: "f", arabic: "\u0647", color: "#F5F5DC" },
    { id: 7, english: "%", arabic: "\u066A", color: "#FFFFFF" },
  ],
  [
    { id: 8, english: "y", arabic: ">", color: "#FFFFFF" },
    { id: 9, english: "g", arabic: "\u0641", color: "#98FB98" },
    { id: 10, english: "h", arabic: "\u0645", color: "#98FB98" },
    { id: 11, english: "i", arabic: "\u0643", color: "#ADD8E6" },
    { id: 12, english: "j", arabic: "\u0633", color: "#FFC0CB" },
    { id: 13, english: "k", arabic: "\u062d", color: "#FFC0CB" },
    { id: 14, english: "l", arabic: "\u0639", color: "#FFC0CB" },
  ],
  [
    { id: 15, english: "m", arabic: "\u066D", color: "#FFD700" },
    { id: 16, english: "n", arabic: "\u066E", color: "#98FB98" },
    { id: 17, english: "o", arabic: "\u0646", color: "#FFC0CB" },
    { id: 18, english: "p", arabic: "\u0631", color: "#FFC0CB" },
    { id: 19, english: "q", arabic: "\u0635", color: "#FFC0CB" },
    { id: 20, english: "r", arabic: "\u0621", color: "#FFD700" },
    { id: 21, english: "z", arabic: "_", color: "#FFFFFF" },
  ],
  [
    { id: 22, english: "%", arabic: "_", color: "#FFFFFF" },
    { id: 23, english: "s", arabic: "\u0637", color: "#98FB98" },
    { id: 24, english: "t", arabic: "\u062F", color: "#ADD8E6" },
    { id: 25, english: "u", arabic: "\u0644", color: "#D8BFD8" },
    { id: 26, english: "v", arabic: "\u0627", color: "#FAEBD7" },
    { id: 27, english: "w", arabic: "\u0648", color: "#ADD8E6" },
    { id: 28, english: "x", arabic: "\u064A", color: "#D8BFD8" },
    { id: 29, english: "x", arabic: "\u064A", color: "#D8BFD8" },
  ],
];
